### ISSUE TITLE
Create new verification page

### ISSUE THREAD

**Issue by Dolu89** [whiteyhat/Avicenna#13]
## Introduction
Create a verification page to prove the authenticity of the Avicenna's passport

## To-Do Tasks
- [x] Create a tab view
- [x] Tab 1 : https://github.com/whiteyhat/Avicenna/wiki/Passport-Validation-Guidelines
- [x] Tab 2 : uuid + auth token => digest message
- [x] Tab 3 : IPFS hash sha256 = digest message
